<?php

class model_showcart3 extends Model
{

    function __construct()
    {
        parent::__construct();
    }


    function getBasketReview()
    {
        return parent::getBasket(); // TODO: Change the autogenerated stub
    }

    function postPrice()
    {

        self::sessionInit();
        $addressInfo = self::sessionGet('addressInfo');
        $addressInfo = unserialize($addressInfo);


    }


}
